"""Assemble this one editorial example; requires the pandoc command."""

from pathlib import Path
import subprocess


def build() -> None:
    root = Path(__file__).resolve().parent
    source = root / "source"
    output = root / "generated"
    output.mkdir(exist_ok=True)
    notice = "<!-- Generated by ../build.py from ../source/. Do not edit; rebuild instead. -->\n\n"
    page = notice + (source / "page.md").read_text()
    for name in ("cowork", "government"):
        page = page.replace("{{" + name + "}}", (source / "variants" / f"{name}.md").read_text().rstrip())
    (output / "after.md").write_text(page)
    subprocess.run(
        ["pandoc", str(output / "after.md"), "--standalone", "--metadata", "pagetitle=Install a plugin",
         "--include-in-header", str(source / "preview-head.html"), "--output", str(output / "after.html")],
        check=True,
    )


if __name__ == "__main__":
    build()
