"""Build the worked rewrite and optionally serve its standalone preview."""

import argparse
from functools import partial
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
import re
import webbrowser

import frontmatter
from jinja2 import Environment, FileSystemLoader, StrictUndefined, select_autoescape
from markdown import markdown

ROOT = Path(__file__).resolve().parent
NOTICE = "<!-- Generated by build.py from source/. Do not edit; rebuild instead. -->\n"


def render(root: Path = ROOT) -> dict[str, str]:
    """Compose Markdown, then render it inside the HTML template."""
    templates = Environment(
        loader=FileSystemLoader(root / "source"),
        undefined=StrictUndefined,
        autoescape=select_autoescape(["html"]),
        # Leave Markdown's {#heading-id} attributes intact.
        comment_start_string="{##",
        comment_end_string="##}",
        keep_trailing_newline=True,
    )
    variants = []
    for path in sorted((root / "source" / "variants").glob("*.md")):
        if not re.fullmatch(r"[a-z][a-z0-9-]*", path.stem) or path.stem == "all":
            raise ValueError(f"{path.name}: use a lowercase slug other than 'all'")
        post = frontmatter.loads(path.read_text(encoding="utf-8"))
        label = post.get("label", path.stem)
        default = post.get("default", False)
        if not isinstance(label, str) or not label.strip() or not isinstance(default, bool):
            raise ValueError(f"{path.name}: label must be nonempty text and default must be a boolean")
        variants.append(dict(id=path.stem, label=label, content=post.content, default=default))
    if not variants:
        raise ValueError("Add at least one Markdown file to source/variants/")
    defaults = [variant["id"] for variant in variants if variant["default"]]
    if len(defaults) > 1:
        raise ValueError("Only one variant may have default: true")
    page = templates.get_template("page.md").render(
        variants=variants, default_variant=next(iter(defaults), "")
    ).rstrip() + "\n"
    body = markdown(page, extensions=["md_in_html", "attr_list", "toc", "fenced_code", "tables"])
    html = templates.get_template("templates/page.html").render(title="Install a plugin", body=body)
    return {"page.md": NOTICE + "\n" + page, "page.html": NOTICE + html}


def build() -> Path:
    """Write both outputs only after all templates render successfully."""
    artifacts = render()
    output = ROOT / "build"
    output.mkdir(exist_ok=True)
    for name, content in artifacts.items():
        (output / name).write_text(content, encoding="utf-8", newline="\n")
    print(f"Built {output / 'page.html'}", flush=True)
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["build", "serve"], nargs="?", default="build")
    parser.add_argument("--port", type=int, default=8765, help="Preview port (default: 8765)")
    parser.add_argument("--open", action="store_true", help="Open the preview in your browser")
    args = parser.parse_args()
    if not 0 <= args.port <= 65535:
        parser.error("--port must be between 0 and 65535")
    output = build()
    if args.command == "build":
        if args.open:
            webbrowser.open((output / "page.html").as_uri())
        return
    handler = partial(SimpleHTTPRequestHandler, directory=str(output))
    try:
        server = ThreadingHTTPServer(("127.0.0.1", args.port), handler)
    except OSError as error:
        parser.exit(1, f"Cannot start preview: {error}. Try --port with another port.\n")
    with server:
        url = f"http://127.0.0.1:{server.server_port}/page.html"
        print(f"Preview: {url}\nPress Ctrl+C to stop. Rebuild and refresh after editing.", flush=True)
        if args.open:
            webbrowser.open(url)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
